title:            NS Labs
description:      Blog technique de Natural Solutions
logo:             logo-ns.png
disqus_shortname:
search:           true
# Change url to your domain. Leave localhost server or blank when working locally.
# You don't need to specify the protocol if you want it available on http and https. Example: //localhost:4000
url:
  host:           //naturalsolution.github.io
  prefix:         

# Owner/author information
owner:
  name:           Natural Solutions
  avatar:         bio-photo.jpg
  email:          contact@natural-solutions.eu
  # Social networking links used in footer. Update and remove as you like.
  twitter:        orovellotti
  facebook:       myNaturalSolutions
  github:         NaturalSolutions
  stackexchange:
  linkedin:       natural-solutions
  instagram:
  flickr:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:  UA-52696458-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Ã€ propos
    url: /apropos/
  - title: Articles
    url: /articles/
  - title: Natural Solutions
    url: http://www.natural-solutions.eu/
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Paris
future:      true
pygments:    true
#highlighter: pygments
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   date

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "README.md", "LICENSE", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
